// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Common/Form/ValidationTextBox',
    'Sds/IdentityModule/DataModel/Identity/Lastname/Validator'
],
function(
    declare,
    ValidationTextBox,
    LastnameValidator
){
    // Will return an Input for the lastname field

    return declare(
        'Sds/IdentityModule/DataModel/Identity/Lastname/Input',
        [ValidationTextBox],
        {
            validator: new LastnameValidator,

            name: "lastname",

            label: "Lastname:"
        }
    );
});
