// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Validator/ValidatorGroup',
    'Sds/Validator/RequiredValidator',
    'Sds/Validator/PersonalNameValidator'
],
function(
    declare,
    ValidatorGroup,
    RequiredValidator,
    PersonalNameValidator
){
    // Will return a validator that can be used to check
    // the lastname field

    return declare(
        'Sds/IdentityModule/DataModel/Identity/Lastname/Validator',
        [ValidatorGroup],
        {
            field: "lastname",

            validators: [
                new RequiredValidator,
                new PersonalNameValidator
            ]
        }
    );
});
