// This code generated by Sds\DoctrineExtensions\DojoModel

define ([
        'dojo/_base/declare',
        'dojo/Stateful'
    ],
    function (
        declare,
        Stateful
    ){
        // module:
        //		Sds/IdentityModule/DataModel/Identity

        var model = declare (
            'Sds/IdentityModule/DataModel/Identity',
            [Stateful],
            {
                // summary:
                //		A mirror of doctrine document Sds\IdentityModule\DataModel\Identity
                //
                // description:
                //      Use this to create documents in a browser which can the be passed to a doctrine server for
                //      persistence

                // _className: string
                //      The doctrine document class name. Don't change this one!
                _className: 'Sds\\IdentityModule\\DataModel\\Identity',

                // id: custom_id
                id: undefined,

                // firstname: string
                firstname: undefined,

                // lastname: string
                lastname: undefined,

                // email: string
                email: undefined,

                // profile: one
                profile: undefined,

                // forgotCredentialCode: string
                forgotCredentialCode: undefined,

                // credential: string
                credential: undefined,

                // identityName: string
                identityName: undefined,

                // roles: hash
                roles: undefined,

                toJSON: function(){
                    // summary:
                    //     Function to handle serialization

                    var json = {};
                    if (this.get('_className')) {
                        json['_className'] = this.get('_className');
                    }
                    if (this.get('id')) {
                        json['id'] = this.get('id');
                    }
                    if (this.get('firstname')) {
                        json['firstname'] = this.get('firstname');
                    }
                    if (this.get('lastname')) {
                        json['lastname'] = this.get('lastname');
                    }
                    if (this.get('email')) {
                        json['email'] = this.get('email');
                    }
                    if (this.get('profile')) {
                        json['profile'] = this.get('profile');
                    }
                    if (this.get('forgotCredentialCode')) {
                        json['forgotCredentialCode'] = this.get('forgotCredentialCode');
                    }
                    if (this.get('credential')) {
                        json['credential'] = this.get('credential');
                    }
                    if (this.get('identityName')) {
                        json['identityName'] = this.get('identityName');
                    }
                    if (this.get('roles')) {
                        json['roles'] = this.get('roles');
                    }

                    return json;
                }
            }
        );

        model.metadata = {
            "fields": {
                "id": {
                    "id": "idField",
                    "property": "id",
                    "label": "Id:",
                    "dataType": "custom_id",
                    "inputType": "hidden"
                },
                "firstname": {
                    "id": "firstnameField",
                    "property": "firstname",
                    "label": "Firstname:",
                    "dataType": "string",
                    "validatorGroup": [
                        {
                            "class": "Sds\/Common\/Validator\/RequiredValidator"
                        },
                        {
                            "class": "Sds\/Common\/Validator\/PersonalNameValidator",
                            "options": null
                        }
                    ]
                },
                "lastname": {
                    "id": "lastnameField",
                    "property": "lastname",
                    "label": "Lastname:",
                    "dataType": "string",
                    "validatorGroup": [
                        {
                            "class": "Sds\/Common\/Validator\/RequiredValidator"
                        },
                        {
                            "class": "Sds\/Common\/Validator\/PersonalNameValidator",
                            "options": null
                        }
                    ]
                },
                "email": {
                    "id": "emailField",
                    "property": "email",
                    "label": "Email:",
                    "dataType": "string",
                    "validatorGroup": [
                        {
                            "class": "Sds\/Common\/Validator\/RequiredValidator"
                        },
                        {
                            "class": "Sds\/Common\/Validator\/EmailAddressValidator",
                            "options": null
                        }
                    ]
                },
                "profile": {
                    "id": "profileField",
                    "property": "profile",
                    "label": "Profile:",
                    "dataType": "one"
                },
                "forgotCredentialCode": {
                    "id": "forgotCredentialCodeField",
                    "property": "forgotCredentialCode",
                    "label": "Forgot Credential Code:",
                    "dataType": "string"
                },
                "credential": {
                    "id": "credentialField",
                    "property": "credential",
                    "label": "Password:",
                    "dataType": "string",
                    "validatorGroup": [
                        {
                            "class": "Sds\/Common\/Validator\/RequiredValidator"
                        },
                        {
                            "class": "Sds\/Common\/Validator\/CredentialValidator",
                            "options": null
                        }
                    ],
                    "type": "password"
                },
                "identityName": {
                    "id": "identityNameField",
                    "property": "identityName",
                    "label": "Username:",
                    "dataType": "string",
                    "validatorGroup": [
                        {
                            "class": "Sds\/Common\/Validator\/RequiredValidator"
                        },
                        {
                            "class": "Sds\/Common\/Validator\/IdentifierValidator",
                            "options": null
                        }
                    ]
                },
                "roles": {
                    "id": "rolesField",
                    "property": "roles",
                    "label": "Roles:",
                    "dataType": "hash",
                    "validatorGroup": [
                        {
                            "class": "Sds\/Common\/Validator\/NotRequiredValidator"
                        },
                        {
                            "class": "Sds\/Validator\/IdentifierArrayValidator",
                            "options": null
                        }
                    ]
                }
            }
        };

        return model;
    }
);
