// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'dojo/_base/lang',
    'Sds/Store/JsonRest'
],
function(
    declare,
    lang,
    JsonRest
){

    return declare(
        'Sds/Mvc/JsonRest',
        [JsonRest],
        {

            name: undefined,

            model: undefined,

            get: function(id){
                var result = this.inherited(arguments);
                if (result){
                    return declare.safeMixin(new this.model, result);
                } else {
                    return null;
                }
            },

            query: function(query, options){
                return this.inherited(arguments).map(lang.hitch(this, function(object){
                    return declare.safeMixin(new this.model, object);
                }));
            }
        }
    );
});
