define([
    'Sds/Test/Validator/TestAlphaValidator',
    'Sds/Test/Validator/TestBaseValidator',
    'Sds/Test/Validator/TestCvvValidator',    
    'Sds/Test/Validator/TestCredentialValidator',
    'Sds/Test/Validator/TestCreditCardExpiryValidator',      
    'Sds/Test/Validator/TestCreditCardValidator',    
    'Sds/Test/Validator/TestCurrencyValidator',
    'Sds/Test/Validator/TestDatatypeValidator',
    'Sds/Test/Validator/TestEmailAddressValidator',
    'Sds/Test/Validator/TestLengthValidator',
    'Sds/Test/Validator/TestModelValidator',
    'Sds/Test/Validator/TestIdentifierArrayValidator',
    'Sds/Test/Validator/TestIdentifierValidator',
    'Sds/Test/Validator/TestInequalityValidator',
    'Sds/Test/Validator/TestRequiredValidator',
    'Sds/Test/Validator/TestValidatorGroup',
    'Sds/Test/Validator/TestValidatorFactory'
], 1);
