// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Common/Form/ValidationForm',
    
],
function(
    declare,
    ValidationForm,
    
){
    // Will return a form

    return declare(
        'Sds/IdentityModule/DataModel/Profile/Form',
        [ValidationForm],
        {

            

            inputs: [
                
            ]
        }
    );
});
