// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Mvc/BaseModelJsonRestStore',
    'Sds/IdentityModule/DataModel/Profile'
],
function(
    declare,
    BaseJsonRestStore,
    Profile
){
    // Will return dojo object store to manage server model
    // instances with a json rest api.

    return declare(
        'Sds/IdentityModule/DataModel/Profile/JsonRestStore',
        [BaseJsonRestStore],
        {

            name: 'Profile',

            idProperty: '',

            target: 'http://localhost/ZendSkeletonApplication/IdentityModule/Profile/',

            model: Profile
        }
    );
});
