// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',    
    'Sds/Form/ValidationTextBox',
    'Sds/IdentityModule/DataModel/Profile/IdentityName/Validator'
],
function(
    declare,    
    ValidationTextBox,
    IdentityNameValidator
){
    // Will return an input for the identityName field

    return declare(
        'Sds/IdentityModule/DataModel/Profile/IdentityName/Input',
        [            
            ValidationTextBox        
        ],
        {
            type: 'hidden',
            
            validator: new IdentityNameValidator,
            
            name: 'identityName',
            
            label: 'Identity Name'
        }
    );
});
