// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Common/Form/ValidationTextBox',
    'Sds/IdentityModule/DataModel/Identity/Firstname/Validator'
],
function(
    declare,
    ValidationTextBox,
    FirstnameValidator
){
    // Will return an Input for the firstname field

    return declare(
        'Sds/IdentityModule/DataModel/Identity/Firstname/Input',
        [ValidationTextBox],
        {
            validator: new FirstnameValidator,

            name: "firstname",

            label: "Firstname:"
        }
    );
});
