// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Common/Form/TextBox'
],
function(
    declare,
    TextBox
){
    // Will return an Input for the identityName field

    return declare(
        'Sds/IdentityModule/DataModel/ForgotCredentialToken/IdentityName/Input',
        [TextBox],
        {
            name: "identityName",

            label: "Identity Name:"
        }
    );
});
