// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Common/Validator/ValidatorGroup',
    'Sds/Common/Validator/RequiredValidator',
    'Sds/Common/Validator/IdentifierValidator'
],
function(
    declare,
    ValidatorGroup,
    RequiredValidator,
    IdentifierValidator
){
    // Will return a validator that can be used to check
    // the identityName field

    return declare(
        'Sds/IdentityModule/DataModel/ForgotCredentialToken/IdentityName/Validator',
        [ValidatorGroup],
        {
            field: "identityName",

            validators: [
                new RequiredValidator,
                new IdentifierValidator
            ]
        }
    );
});
