// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',    
    'Sds/Form/ValidationTextBox',
    'Sds/IdentityModule/DataModel/Identity/Email/Validator'
],
function(
    declare,    
    ValidationTextBox,
    EmailValidator
){
    // Will return an input for the email field

    return declare(
        'Sds/IdentityModule/DataModel/Identity/Email/Input',
        [            
            ValidationTextBox        
        ],
        {
            validator: new EmailValidator,
            
            name: 'email',
            
            label: 'Email'
        }
    );
});
