// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Validator/ValidatorGroup',
    'Sds/Validator/RequiredValidator',
    'Sds/Validator/EmailAddressValidator'
],
function(
    declare,
    ValidatorGroup,
    RequiredValidator,
    EmailAddressValidator
){
    // Will return a validator that can be used to check
    // the email field

    return declare(
        'Sds/IdentityModule/DataModel/Identity/Email/Validator',
        [ValidatorGroup],
        {
            field: "email",

            validators: [
                new RequiredValidator,
                new EmailAddressValidator
            ]
        }
    );
});
