// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',    
    'Sds/Validator/Group',
    'Sds/Validator/Required',
    'Sds/Validator/EmailAddress'
],
function(
    declare,    
    Group,
    Required,
    EmailAddress
){
    // Will return a validator that can be used to check
    // the email field

    return declare(
        'Sds/IdentityModule/DataModel/Identity/Email/Validator',
        [            
            Group        
        ],
        {
            field: 'email',
            
            validators: [
            	new Required,
            	new EmailAddress
            ]
        }
    );
});
