// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Common/Form/TextBox'
],
function(
    declare,
    TextBox
){
    // Will return an Input for the profile field

    return declare(
        'Sds/IdentityModule/DataModel/Identity/Profile/Input',
        [TextBox],
        {
            name: "profile",

            label: "Profile:"
        }
    );
});
