// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',    
    'Sds/Form/ValidationTextBox',
    'Sds/IdentityModule/DataModel/Profile/Firstname/Validator'
],
function(
    declare,    
    ValidationTextBox,
    FirstnameValidator
){
    // Will return an input for the firstname field

    return declare(
        'Sds/IdentityModule/DataModel/Profile/Firstname/Input',
        [            
            ValidationTextBox        
        ],
        {
            validator: new FirstnameValidator,
            
            name: 'firstname',
            
            label: 'Firstname'
        }
    );
});
