// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',    
    'Sds/Validator/Group',
    'Sds/Validator/Required',
    'Sds/Validator/PersonalName'
],
function(
    declare,    
    Group,
    Required,
    PersonalName
){
    // Will return a validator that can be used to check
    // the lastname field

    return declare(
        'Sds/IdentityModule/DataModel/Identity/Lastname/Validator',
        [            
            Group        
        ],
        {
            field: 'lastname',
            
            validators: [
            	new Required,
            	new PersonalName
            ]
        }
    );
});
