// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Mvc/BaseModel'
],
function(
    declare,
    BaseModel
){
    // Will return an object representing the document
    // which can be serialized to json.

    return declare(
        'Sds/IdentityModule/DataModel/ForgotCredentialToken',
        [BaseModel],
        {

            _fields: [
                "code",
                "identityName",
                "expires"
            ]
        }
    );
});
