// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Mvc/BaseModel'
],
function(
    declare,
    BaseModel
){
    // Will return an object representing the document
    // which can be serialized to json.

    return declare(
        'Sds/IdentityModule/DataModel/Identity',
        [BaseModel],
        {

            _fields: [
                "firstname",
                "lastname",
                "email",
                "profile",
                "credential",
                "identityName",
                "roles",
                "_className"
            ],
            _className: 'Sds\\IdentityModule\\DataModel\\Identity',
            _validatorMid: 'Sds/IdentityModule/DataModel/Identity/ModelValidator'
        }
    );
});
