// This code generated by Sds\DoctrineExtensions\Dojo

define ([], function (){

    return {
        moduleManager: {

            // Will return an object representing the document
            // which can be serialized to json.
            'Sds/IdentityModule/DataModel/Identity': {
                base: 'Sds/Mvc/BaseModel',
                directives: {
                    declare: true
                },
                params: {
                    _fields: [
                        "id",
                        "firstname",
                        "lastname",
                        "email",
                        "profile",
                        "forgotCredentialCode",
                        "credential",
                        "identityName",
                        "roles",
                        "_className"
                    ],
                    _className: 'Sds\\IdentityModule\\DataModel\\Identity'
                }
            },

            // Will return an validator that can be used to validate
            // a complete instance of the document/model
            'Sds/IdentityModule/DataModel/Identity/validator': {
                base: 'modelValidator',
                gets: {
                    validators: [
                        "Sds\/IdentityModule\/DataModel\/Identity\/Firstname\/validator",
                        "Sds\/IdentityModule\/DataModel\/Identity\/Lastname\/validator",
                        "Sds\/IdentityModule\/DataModel\/Identity\/Email\/validator",
                        "Sds\/IdentityModule\/DataModel\/Identity\/Credential\/validator",
                        "Sds\/IdentityModule\/DataModel\/Identity\/IdentityName\/validator",
                        "Sds\/IdentityModule\/DataModel\/Identity\/Roles\/validator"
                    ]
                }
            },

            // Will return a validator that can be used to check
            // the firstname field
            'Sds/IdentityModule/DataModel/Identity/Firstname/validator': {
                "base": "validatorGroup",
                "gets": {
                    "validators": [
                        "Sds\/Common\/Validator\/RequiredValidator",
                        "Sds\/Common\/Validator\/PersonalNameValidator"
                    ]
                },
                "params": {
                    "field": "firstname"
                }
            },

            // Will return a validator that can be used to check
            // the lastname field
            'Sds/IdentityModule/DataModel/Identity/Lastname/validator': {
                "base": "validatorGroup",
                "gets": {
                    "validators": [
                        "Sds\/Common\/Validator\/RequiredValidator",
                        "Sds\/Common\/Validator\/PersonalNameValidator"
                    ]
                },
                "params": {
                    "field": "lastname"
                }
            },

            // Will return a validator that can be used to check
            // the email field
            'Sds/IdentityModule/DataModel/Identity/Email/validator': {
                "base": "validatorGroup",
                "gets": {
                    "validators": [
                        "Sds\/Common\/Validator\/RequiredValidator",
                        "Sds\/Common\/Validator\/EmailAddressValidator"
                    ]
                },
                "params": {
                    "field": "email"
                }
            },

            // Will return a validator that can be used to check
            // the credential field
            'Sds/IdentityModule/DataModel/Identity/Credential/validator': {
                "base": "validatorGroup",
                "gets": {
                    "validators": [
                        "Sds\/Common\/Validator\/RequiredValidator",
                        "Sds\/Common\/Validator\/CredentialValidator"
                    ]
                },
                "params": {
                    "field": "credential"
                }
            },

            // Will return a validator that can be used to check
            // the identityName field
            'Sds/IdentityModule/DataModel/Identity/IdentityName/validator': {
                "base": "validatorGroup",
                "gets": {
                    "validators": [
                        "Sds\/Common\/Validator\/RequiredValidator",
                        "Sds\/Common\/Validator\/IdentifierValidator"
                    ]
                },
                "params": {
                    "field": "identityName"
                }
            },

            // Will return a validator that can be used to check
            // the roles field
            'Sds/IdentityModule/DataModel/Identity/Roles/validator': {
                "base": "validatorGroup",
                "gets": {
                    "validators": [
                        "Sds\/Common\/Validator\/IdentifierArrayValidator"
                    ]
                },
                "params": {
                    "field": "roles"
                }
            },

            // Will return a form
            'Sds/IdentityModule/DataModel/Identity/Form': {
                "base": "Sds\/Common\/Form\/ValidationForm",
                "directives": {
                    "define": true,
                    "declare": true
                },
                "gets": {
                    "inputs": [
                        "Sds\/IdentityModule\/DataModel\/Identity\/Id\/Input",
                        "Sds\/IdentityModule\/DataModel\/Identity\/Firstname\/Input",
                        "Sds\/IdentityModule\/DataModel\/Identity\/Lastname\/Input",
                        "Sds\/IdentityModule\/DataModel\/Identity\/Email\/Input",
                        "Sds\/IdentityModule\/DataModel\/Identity\/Profile\/Input",
                        "Sds\/IdentityModule\/DataModel\/Identity\/ForgotCredentialCode\/Input",
                        "Sds\/IdentityModule\/DataModel\/Identity\/Credential\/Input",
                        "Sds\/IdentityModule\/DataModel\/Identity\/IdentityName\/Input",
                        "Sds\/IdentityModule\/DataModel\/Identity\/Roles\/Input"
                    ]
                }
            },

            // Will return an Input for the id field
            'Sds/IdentityModule/DataModel/Identity/Id/Input': {
                "base": "Sds\/Common\/Form\/TextBox",
                "directives": {
                    "define": true,
                    "declare": true
                },
                "params": {
                    "name": "id",
                    "label": "Id:",
                    "type": "hidden"
                }
            },

            // Will return an Input for the firstname field
            'Sds/IdentityModule/DataModel/Identity/Firstname/Input': {
                "base": "Sds\/Common\/Form\/ValidationTextBox",
                "gets": {
                    "validator": "Sds\/IdentityModule\/DataModel\/Identity\/Firstname\/validator"
                },
                "directives": {
                    "define": true,
                    "declare": true
                },
                "params": {
                    "name": "firstname",
                    "label": "Firstname:"
                }
            },

            // Will return an Input for the lastname field
            'Sds/IdentityModule/DataModel/Identity/Lastname/Input': {
                "base": "Sds\/Common\/Form\/ValidationTextBox",
                "gets": {
                    "validator": "Sds\/IdentityModule\/DataModel\/Identity\/Lastname\/validator"
                },
                "directives": {
                    "define": true,
                    "declare": true
                },
                "params": {
                    "name": "lastname",
                    "label": "Lastname:"
                }
            },

            // Will return an Input for the email field
            'Sds/IdentityModule/DataModel/Identity/Email/Input': {
                "base": "Sds\/Common\/Form\/ValidationTextBox",
                "gets": {
                    "validator": "Sds\/IdentityModule\/DataModel\/Identity\/Email\/validator"
                },
                "directives": {
                    "define": true,
                    "declare": true
                },
                "params": {
                    "name": "email",
                    "label": "Email:"
                }
            },

            // Will return an Input for the profile field
            'Sds/IdentityModule/DataModel/Identity/Profile/Input': {
                "base": "Sds\/Common\/Form\/TextBox",
                "directives": {
                    "define": true,
                    "declare": true
                },
                "params": {
                    "name": "profile",
                    "label": "Profile:"
                }
            },

            // Will return an Input for the forgotCredentialCode field
            'Sds/IdentityModule/DataModel/Identity/ForgotCredentialCode/Input': {
                "base": "Sds\/Common\/Form\/TextBox",
                "directives": {
                    "define": true,
                    "declare": true
                },
                "params": {
                    "name": "forgotCredentialCode",
                    "label": "Forgot Credential Code:"
                }
            },

            // Will return an Input for the credential field
            'Sds/IdentityModule/DataModel/Identity/Credential/Input': {
                "base": "Sds\/Common\/Form\/ValidationTextBox",
                "gets": {
                    "validator": "Sds\/IdentityModule\/DataModel\/Identity\/Credential\/validator"
                },
                "directives": {
                    "define": true,
                    "declare": true
                },
                "params": {
                    "name": "credential",
                    "label": "Password:",
                    "type": "password"
                }
            },

            // Will return an Input for the identityName field
            'Sds/IdentityModule/DataModel/Identity/IdentityName/Input': {
                "base": "Sds\/Common\/Form\/ValidationTextBox",
                "gets": {
                    "validator": "Sds\/IdentityModule\/DataModel\/Identity\/IdentityName\/validator"
                },
                "directives": {
                    "define": true,
                    "declare": true
                },
                "params": {
                    "name": "identityName",
                    "label": "Username:"
                }
            },

            // Will return an Input for the roles field
            'Sds/IdentityModule/DataModel/Identity/Roles/Input': {
                "base": "Sds\/Common\/Form\/ValidationTextBox",
                "gets": {
                    "validator": "Sds\/IdentityModule\/DataModel\/Identity\/Roles\/validator"
                },
                "directives": {
                    "define": true,
                    "declare": true
                },
                "params": {
                    "name": "roles",
                    "label": "Roles:"
                }
            }
        }
    };
});
