// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',    
    'Sds/Mvc/BaseModel'
],
function(
    declare,    
    BaseModel
){
    // Will return a model for Sds\IdentityModule\DataModel\Identity

    return declare(
        'Sds/IdentityModule/DataModel/Identity',
        [            
            BaseModel        
        ],
        {
            _fields: [
            	"email",
            	"profile",
            	"credential",
            	"identityName",
            	"roles",
            	"_className"
            ],
            
            _className: 'Sds\\IdentityModule\\DataModel\\Identity'
        }
    );
});
