// This code generated by Sds\DoctrineExtensions\Dojo

define ([], function (){

    return {
        moduleManager: {

            // Will return an object representing the document
            // which can be serialized to json.
            'Sds/IdentityModule/DataModel/Profile': {
                base: 'Sds/Mvc/BaseModel',
                directives: {
                    declare: true
                },
                params: {
                    _fields: [
                        "_className"
                    ],
                    _className: 'Sds\\IdentityModule\\DataModel\\Profile'
                }
            },

            // Will return a form
            'Sds/IdentityModule/DataModel/Profile/Form': {
                "base": "Sds\/Common\/Form\/ValidationForm",
                "directives": {
                    "define": true,
                    "declare": true
                },
                "gets": {
                    "inputs": [
            
                    ]
                }
            }
        }
    };
});
