// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Common/Form/ValidationForm',
    'Sds/IdentityModule/DataModel/ForgotCredentialToken/Code/Input',
    'Sds/IdentityModule/DataModel/ForgotCredentialToken/IdentityName/Input',
    'Sds/IdentityModule/DataModel/ForgotCredentialToken/Expires/Input'
],
function(
    declare,
    ValidationForm,
    CodeInput,
    IdentityNameInput,
    ExpiresInput
){
    // Will return a form

    return declare(
        'Sds/IdentityModule/DataModel/ForgotCredentialToken/Form',
        [ValidationForm],
        {

            

            inputs: [
                new CodeInput,
                new IdentityNameInput,
                new ExpiresInput
            ]
        }
    );
});
