// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Mvc/BaseModelJsonRestStore',
    'Sds/IdentityModule/DataModel/ForgotCredentialToken'
],
function(
    declare,
    BaseJsonRestStore,
    ForgotCredentialToken
){
    // Will return dojo object store to manage server model
    // instances with a json rest api.

    return declare(
        'Sds/IdentityModule/DataModel/ForgotCredentialToken/JsonRestStore',
        [BaseJsonRestStore],
        {

            name: 'ForgotCredentialToken',

            idProperty: 'code',

            target: 'http://localhost/ZendSkeletonApplication/IdentityModule/ForgotCredentialToken/',

            model: ForgotCredentialToken
        }
    );
});
