// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',    
    'Sds/Mvc/JsonRest',
    'Sds/IdentityModule/DataModel/ForgotCredentialToken'
],
function(
    declare,    
    JsonRest,
    ForgotCredentialToken
){
    // Will return create a dojo JsonRest store for Sds\IdentityModule\DataModel\ForgotCredentialToken

    return declare(
        'Sds/IdentityModule/DataModel/ForgotCredentialToken/JsonRest',
        [            
            JsonRest        
        ],
        {
            name: 'ForgotCredentialToken',
            
            idProperty: 'code',
            
            target: 'http://localhost/ZendSkeletonApplication/forgotcredentialtoken',
            
            model: ForgotCredentialToken
        }
    );
});
