// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Common/Form/ValidationTextBox',
    'Sds/IdentityModule/DataModel/Identity/Credential/Validator'
],
function(
    declare,
    ValidationTextBox,
    CredentialValidator
){
    // Will return an Input for the credential field

    return declare(
        'Sds/IdentityModule/DataModel/Identity/Credential/Input',
        [ValidationTextBox],
        {
            validator: new CredentialValidator,

            name: "credential",

            label: "Password:",

            type: "password"
        }
    );
});
