// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',    
    'Sds/Form/PasswordTextBox',
    'Sds/IdentityModule/DataModel/Identity/Credential/Validator'
],
function(
    declare,    
    PasswordTextBox,
    CredentialValidator
){
    // Will return an input for the credential field

    return declare(
        'Sds/IdentityModule/DataModel/Identity/Credential/Input',
        [            
            PasswordTextBox        
        ],
        {
            validator: new CredentialValidator,
            
            name: 'credential',
            
            label: 'Credential'
        }
    );
});
