// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Validator/ValidatorGroup',
    'Sds/Validator/RequiredValidator',
    'Sds/Validator/CredentialValidator'
],
function(
    declare,
    ValidatorGroup,
    RequiredValidator,
    CredentialValidator
){
    // Will return a validator that can be used to check
    // the credential field

    return declare(
        'Sds/IdentityModule/DataModel/Identity/Credential/Validator',
        [ValidatorGroup],
        {
            field: "credential",

            validators: [
                new RequiredValidator,
                new CredentialValidator
            ]
        }
    );
});
