// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',    
    'Sds/Validator/Group',
    'Sds/Validator/Required',
    'Sds/Validator/Identifier'
],
function(
    declare,    
    Group,
    Required,
    Identifier
){
    // Will return a validator that can be used to check
    // the identityName field

    return declare(
        [            
            Group        
        ],
        {
            field: 'identityName',
            
            validators: [
            	new Required,
            	new Identifier
            ]
        }
    );
});
