// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Common/Form/ValidationForm',
    'Sds/IdentityModule/DataModel/Identity/Firstname/Input',
    'Sds/IdentityModule/DataModel/Identity/Lastname/Input',
    'Sds/IdentityModule/DataModel/Identity/Email/Input',
    'Sds/IdentityModule/DataModel/Identity/Profile/Input',
    'Sds/IdentityModule/DataModel/Identity/Credential/Input',
    'Sds/IdentityModule/DataModel/Identity/IdentityName/Input',
    'Sds/IdentityModule/DataModel/Identity/Roles/Input'
],
function(
    declare,
    ValidationForm,
    FirstnameInput,
    LastnameInput,
    EmailInput,
    ProfileInput,
    CredentialInput,
    IdentityNameInput,
    RolesInput
){
    // Will return a form

    return declare(
        'Sds/IdentityModule/DataModel/Identity/Form',
        [ValidationForm],
        {

            

            inputs: [
                new FirstnameInput,
                new LastnameInput,
                new EmailInput,
                new ProfileInput,
                new CredentialInput,
                new IdentityNameInput,
                new RolesInput
            ]
        }
    );
});
