// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Mvc/BaseModelJsonRestStore',
    'Sds/IdentityModule/DataModel/Identity'
],
function(
    declare,
    BaseModelJsonRestStore,
    Identity
){
    // Will return dojo object store to manage server model
    // instances with a json rest api.

    return declare(
        'Sds/IdentityModule/DataModel/Identity/JsonRestStore',
        [BaseModelJsonRestStore],
        {

            idProperty: 'identityName',

            target: 'Identity',

            model: Identity
        }
    );
});
