// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Mvc/JsonRest',
    'Sds/IdentityModule/DataModel/Identity'
],
function(
    declare,
    JsonRest,
    Identity
){
    // Will return create a dojo JsonRest store for Sds\IdentityModule\DataModel\Identity

    return declare(
        'Sds/IdentityModule/DataModel/Identity/JsonRest',
        [
            JsonRest
        ],
        {
            name: 'Identity',

            idProperty: 'identityName',
            
            target: 'http://localhost/ZendSkeletonApplication/identity/',

            model: Identity
        }
    );
});
