// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',    
    'Sds/Validator/Model',
    'Sds/IdentityModule/DataModel/Identity/Email/Validator',
    'Sds/IdentityModule/DataModel/Identity/Credential/Validator',
    'Sds/IdentityModule/DataModel/Identity/IdentityName/Validator',
    'Sds/IdentityModule/DataModel/Identity/Roles/Validator'
],
function(
    declare,    
    Model,
    EmailValidator,
    CredentialValidator,
    IdentityNameValidator,
    RolesValidator
){
    // Will return a validator to validate a complete model for Sds\IdentityModule\DataModel\Identity

    return declare(
        'Sds/IdentityModule/DataModel/Identity/ModelValidator',
        [            
            Model        
        ],
        {
            validators: [
            	new EmailValidator,
            	new CredentialValidator,
            	new IdentityNameValidator,
            	new RolesValidator
            ]
        }
    );
});
