// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',    
    'Sds/Validator/IdentifierArray'
],
function(
    declare,    
    IdentifierArray
){
    // Will return a validator that can be used to check
    // the roles field

    return declare(
        'Sds/IdentityModule/DataModel/Identity/Roles/Validator',
        [            
            IdentifierArray        
        ],
        {
            field: 'roles'
        }
    );
});
