// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Common/Form/ValidationTextBox',
    'Sds/IdentityModule/DataModel/Identity/IdentityName/Validator'
],
function(
    declare,
    ValidationTextBox,
    IdentityNameValidator
){
    // Will return an Input for the identityName field

    return declare(
        'Sds/IdentityModule/DataModel/Identity/IdentityName/Input',
        [ValidationTextBox],
        {
            validator: new IdentityNameValidator,

            name: "identityName",

            label: "Username:",

            type: "hidden"
        }
    );
});
