// This code generated by Sds\DoctrineExtensions\DojoModel

define ([
        'dojo/_base/declare',
        'dojo/Stateful'
    ],
    function (
        declare,
        Stateful
    ){
        // module:
        //		Sds/UserModule/Model/Profile

        var model = declare (
            'Sds/UserModule/Model/Profile',
            [Stateful],
            {
                // summary:
                //		A mirror of doctrine document Sds\UserModule\Model\Profile
                //
                // description:
                //      Use this to create documents in a browser which can the be passed to a doctrine server for
                //      persistence

                // email: string
                email: undefined,

                toJSON: function(){
                    // summary:
                    //     Function to handle serialization

                    var json = {};
                    if (this.get('email')) {
                        json['email'] = this.get('email');
                    }

                    return json;
                }
            }
        );

        model.metadata = {
            "fields": [
                {
                    "id": "emailField",
                    "property": "email",
                    "title": "Email:",
                    "dataType": "string"
                }
            ]
        };

        return model;
    }
);
