// This code generated by Sds\DoctrineExtensions\DojoModel

define ([
        'dojo/_base/declare',
        'dojo/Stateful'
    ],
    function (
        declare,
        Stateful
    ){
        // module:
        //		Sds/UserModule/Model/User

        return declare (
            'Sds.UserModule.Model.User',
            [Stateful],
            {
                // summary:
                //		A mirror of doctrine document Sds\UserModule\Model\User
                //
                // description:
                //      Use this to create documents in a browser which can the be passed to a doctrine server for
                //      persistence

                // id: custom_id
                id: undefined,

                // firstname: string
                firstname: undefined,

                // lastname: string
                lastname: undefined,

                // nickname: string
                nickname: undefined,

                // password: string
                password: undefined,

                // roles: hash
                roles: undefined,

                // username: string
                username: undefined

            }
        );
    }
);
