// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Common/Form/TextBox'
],
function(
    declare,
    TextBox
){
    // Will return an Input for the expires field

    return declare(
        'Sds/IdentityModule/DataModel/ForgotCredentialToken/Expires/Input',
        [TextBox],
        {
            name: "expires",

            label: "Expires:"
        }
    );
});
