// This code generated by Sds\DoctrineExtensions\DojoModel

define ([
        'dojo/_base/declare',
        'dojo/Stateful'
    ],
    function (
        declare,
        Stateful
    ){
        // module:
        //		Sds/UserModule/DataModel/Profile

        var model = declare (
            'Sds/UserModule/DataModel/Profile',
            [Stateful],
            {
                // summary:
                //		A mirror of doctrine document Sds\UserModule\DataModel\Profile
                //
                // description:
                //      Use this to create documents in a browser which can the be passed to a doctrine server for
                //      persistence

                // _className: string
                //      The doctrine document class name. Don't change this one!
                _className: 'Sds\\UserModule\\DataModel\\Profile',

                // email: string
                email: undefined,

                toJSON: function(){
                    // summary:
                    //     Function to handle serialization

                    var json = {};
                    if (this.get('_className')) {
                        json['_className'] = this.get('_className');
                    }
                    if (this.get('email')) {
                        json['email'] = this.get('email');
                    }

                    return json;
                }
            }
        );

        model.metadata = {
            "fields": {
                "email": {
                    "id": "emailField",
                    "property": "email",
                    "label": "Email:",
                    "dataType": "string",
                    "required": true,
                    "validatorGroup": [
                        {
                            "class": "Sds\/Common\/Validator\/EmailAddressValidator",
                            "options": null
                        }
                    ]
                }
            }
        };

        return model;
    }
);
