// This code generated by Sds\DoctrineExtensions\DojoModel

define ([
        'dojo/_base/declare',
        'dojo/Stateful'
    ],
    function (
        declare,
        Stateful
    ){
        // module:
        //		Sds/UserModule/DataModel/User

        var model = declare (
            'Sds/UserModule/DataModel/User',
            [Stateful],
            {
                // summary:
                //		A mirror of doctrine document Sds\UserModule\DataModel\User
                //
                // description:
                //      Use this to create documents in a browser which can the be passed to a doctrine server for
                //      persistence

                // _className: string
                //      The doctrine document class name. Don't change this one!
                _className: 'Sds\\UserModule\\DataModel\\User',

                // id: custom_id
                id: undefined,

                // firstname: string
                firstname: undefined,

                // lastname: string
                lastname: undefined,

                // profile: one
                profile: undefined,

                // password: string
                password: undefined,

                // roles: hash
                roles: undefined,

                // username: string
                username: undefined,

                toJSON: function(){
                    // summary:
                    //     Function to handle serialization

                    var json = {};
                    if (this.get('_className')) {
                        json['_className'] = this.get('_className');
                    }
                    if (this.get('id')) {
                        json['id'] = this.get('id');
                    }
                    if (this.get('firstname')) {
                        json['firstname'] = this.get('firstname');
                    }
                    if (this.get('lastname')) {
                        json['lastname'] = this.get('lastname');
                    }
                    if (this.get('profile')) {
                        json['profile'] = this.get('profile');
                    }
                    if (this.get('password')) {
                        json['password'] = this.get('password');
                    }
                    if (this.get('roles')) {
                        json['roles'] = this.get('roles');
                    }
                    if (this.get('username')) {
                        json['username'] = this.get('username');
                    }

                    return json;
                }
            }
        );

        model.metadata = {
            "fields": {
                "id": {
                    "id": "idField",
                    "property": "id",
                    "label": "Id:",
                    "dataType": "custom_id",
                    "inputType": "hidden"
                },
                "firstname": {
                    "id": "firstnameField",
                    "property": "firstname",
                    "label": "Firstname:",
                    "dataType": "string",
                    "required": true,
                    "validatorGroup": [
                        {
                            "class": "Sds\/Common\/Validator\/PersonalNameValidator",
                            "options": null
                        }
                    ]
                },
                "lastname": {
                    "id": "lastnameField",
                    "property": "lastname",
                    "label": "Lastname:",
                    "dataType": "string",
                    "required": true,
                    "validatorGroup": [
                        {
                            "class": "Sds\/Common\/Validator\/PersonalNameValidator",
                            "options": null
                        }
                    ]
                },
                "profile": {
                    "id": "profileField",
                    "property": "profile",
                    "label": "Profile:",
                    "dataType": "one"
                },
                "password": {
                    "id": "passwordField",
                    "property": "password",
                    "label": "Password:",
                    "dataType": "string",
                    "required": true,
                    "validatorGroup": [
                        {
                            "class": "Sds\/Common\/Validator\/PasswordValidator",
                            "options": null
                        }
                    ],
                    "type": "password"
                },
                "roles": {
                    "id": "rolesField",
                    "property": "roles",
                    "label": "Roles:",
                    "dataType": "hash",
                    "validatorGroup": [

                    ]
                },
                "username": {
                    "id": "usernameField",
                    "property": "username",
                    "label": "Username:",
                    "dataType": "string",
                    "required": true,
                    "validatorGroup": [
                        {
                            "class": "Sds\/Common\/Validator\/IdentifierValidator",
                            "options": null
                        }
                    ]
                }
            }
        };

        return model;
    }
);
